# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 346756e525d03dcf4eb5da4b9e34942e2e1c400605865d286da6bb3d90bcc8d0aafc44970dbbad478cba87e8d99950c69da256874a0607ee6d6466002ff6334a

test:
  secret_key_base: 900d1d865d84570d4e1aad48b40f83a0dd713393de937bc074d539cd3278b62d289ce3e14e2ca89817a9ebcaf799b10bc7f49109f0b0b0ec48d03e1fe0a07cb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
